# Generated by Django 2.0.7 on 2018-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_auto_20181026_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120),
        ),
    ]
