# Generated by Django 2.1.2 on 2019-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0016_auto_20181217_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120),
        ),
    ]
