# Generated by Django 2.1.2 on 2019-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0017_auto_20190108_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=120),
        ),
    ]
