# Generated by Django 2.1.2 on 2019-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0024_auto_20190110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('billing', 'Billing address'), ('shipping', 'Shipping address'), ('shipping', 'Shipping')], max_length=120),
        ),
    ]
