# Generated by Django 2.1.5 on 2019-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0026_auto_20190114_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing address'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('shipping', 'Shipping address')], max_length=120),
        ),
    ]
