# Generated by Django 2.1.5 on 2019-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0028_auto_20190131_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing address'), ('shipping', 'Shipping'), ('billing', 'Billing'), ('shipping', 'Shipping address')], max_length=120),
        ),
    ]
