# Generated by Django 2.1.5 on 2019-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0031_auto_20190131_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping address'), ('billing', 'Billing address'), ('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120),
        ),
    ]
