# Generated by Django 2.1.2 on 2019-01-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='billing_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
            preserve_default=False,
        ),
    ]
