# Generated by Django 2.1.5 on 2019-01-31 17:50

from django.db import migrations, models
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190130_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
